name: CI/CD for FYHOJ Leaderboard

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build and Test
        run: mvn clean package

  build-and-push-ghcr:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fyhoj-leaderboard:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/fyhoj-leaderboard:${{ github.sha }}

  deploy-to-caprover:
    needs: build-and-push-ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to CapRover
        run: |
          curl -X POST \
            -H "Authorization: ${{ secrets.CAPROVER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"appName": "fyhoj-leaderboard", "imageName": "ghcr.io/'${{ github.repository_owner }}/fyhoj-leaderboard:'${{ github.sha }}'"}' \
            https://your-caprover-domain/api/v2/apps/appDefinitions
